import { useEffect, useMemo, useRef } from 'react'
import type { CSSProperties } from 'react'
import { useTranslation } from 'react-i18next'
import { RefreshCw, Trash2, X } from 'lucide-react'
import type { HighlightsState } from '../../hooks/useEntryHighlights'
import { renderSimpleMarkdown } from '../../lib/simpleMarkdown'
import { Button } from '../common/Button'
import { AiIcon } from '../common/AiIcon'
import { InlineOrb } from '../common/ThinkingOrb'
import { Tooltip } from '../common/Tooltip'

/// Icon-only button override: forces a 28×28 square hit-target so the
/// hover background is symmetric. The shared <Button size="sm"/> defaults
/// to 28px tall + 12px horizontal padding, which renders rectangular when
/// the child is a single icon.
const iconButtonStyle: CSSProperties = { width: 28, padding: 0 }

interface EntryHighlightsPopoverProps {
  state: HighlightsState
  /** Auto-fired once on mount when there's no cached content. The hook
   *  itself is owned by EditorPanel so the stream survives popover
   *  open/close. */
  generate: (force?: boolean) => Promise<void> | void
  cancel: () => Promise<void> | void
  clear: () => Promise<void> | void
  onClose: () => void
}

/**
 * Highlights popover (replaces the inline card under the editor).
 * Anchored above the trigger button via the parent's `relative` wrapper.
 *
 * Behavior:
 * - On first open with no cached/done content → auto-fire `generate()`
 *   so the user doesn't have to click twice.
 * - State persistence is owned by the parent's `useEntryHighlights`
 *   hook, so closing & reopening shows the same stream / cached result.
 */
export function EntryHighlightsPopover({
  state,
  generate,
  cancel,
  clear,
  onClose,
}: EntryHighlightsPopoverProps) {
  const { t, i18n } = useTranslation('ai')

  // Auto-generate on first open if there's nothing to show. Never
  // re-fire on re-render — the parent hook owns persistence.
  const autoGeneratedRef = useRef(false)
  useEffect(() => {
    if (autoGeneratedRef.current) return
    if (state.kind === 'idle' && !state.cached?.markdown) {
      autoGeneratedRef.current = true
      void generate(false)
    }
  }, [state, generate])

  const generatedAtLabel = useMemo(() => {
    let ts: number | null = null
    if (state.kind === 'idle' && state.cached?.generatedAt) ts = state.cached.generatedAt
    if (state.kind === 'done' && state.generatedAt) ts = state.generatedAt
    if (!ts) return null
    return formatRelativeTime(ts, i18n.language)
  }, [state, i18n.language])

  const showRegenerate =
    (state.kind === 'idle' && state.cached?.markdown) ||
    state.kind === 'done' ||
    state.kind === 'error' ||
    state.kind === 'cancelled'

  return (
    <div
      role="dialog"
      aria-label={t('highlights.title', { defaultValue: 'Highlights' })}
      data-testid="entry-highlights-popover"
      className="border-border-default bg-elevated flex max-h-[60vh] w-95 flex-col rounded-xl border shadow-lg"
    >
      <header className="border-border-default flex items-center gap-2 border-b px-3 py-2">
        <AiIcon aria-hidden />
        <span className="text-fg text-sm font-medium">
          {t('highlights.title', { defaultValue: 'Highlights' })}
        </span>
        {generatedAtLabel && <span className="text-fg-secondary text-xs">{generatedAtLabel}</span>}
        {state.kind === 'streaming' && <InlineOrb state="searching" aria-hidden />}
        <span className="ml-auto inline-flex items-center gap-1">
          {showRegenerate && (
            <Tooltip content={t('highlights.regenerate', { defaultValue: 'Regenerate' })}>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => void generate(true)}
                aria-label={t('highlights.regenerate', { defaultValue: 'Regenerate' })}
                style={iconButtonStyle}
                className="justify-center"
              >
                <RefreshCw className="size-3.5" aria-hidden />
              </Button>
            </Tooltip>
          )}
          {(state.kind === 'idle' && state.cached?.markdown) || state.kind === 'done' ? (
            <Tooltip content={t('highlights.clear', { defaultValue: 'Clear' })}>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => void clear()}
                aria-label={t('highlights.clear', { defaultValue: 'Clear' })}
                style={iconButtonStyle}
                className="justify-center"
              >
                <Trash2 className="size-3.5" aria-hidden />
              </Button>
            </Tooltip>
          ) : null}
          {state.kind === 'streaming' && (
            <Tooltip content={t('highlights.cancel', { defaultValue: 'Cancel generation' })}>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => void cancel()}
                style={iconButtonStyle}
                className="justify-center"
              >
                <span className="text-xs">Esc</span>
              </Button>
            </Tooltip>
          )}
          <Tooltip content={t('highlights.close', { defaultValue: 'Close' })}>
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              aria-label={t('highlights.close', { defaultValue: 'Close' })}
              style={iconButtonStyle}
              className="justify-center"
            >
              <X className="size-3.5" aria-hidden />
            </Button>
          </Tooltip>
        </span>
      </header>

      <div className="text-fg-secondary flex-1 overflow-y-auto px-3 py-3 text-sm">
        {state.kind === 'idle' && !state.cached?.markdown && (
          <p className="text-fg-secondary italic">
            {t('highlights.streaming', { defaultValue: 'Generating…' })}
          </p>
        )}
        {state.kind === 'idle' && state.cached?.markdown && (
          <div>{renderSimpleMarkdown(state.cached.markdown)}</div>
        )}
        {state.kind === 'streaming' &&
          (state.partial ? (
            renderSimpleMarkdown(state.partial)
          ) : (
            <p className="text-fg-secondary italic">
              {t('highlights.streaming', { defaultValue: 'Generating…' })}
            </p>
          ))}
        {state.kind === 'done' && <div>{renderSimpleMarkdown(state.markdown)}</div>}
        {state.kind === 'error' && (
          <div className="text-danger-text space-y-1">
            <p>
              {t('highlights.error_unknown', { defaultValue: 'Couldn’t generate highlights.' })}
            </p>
            <p className="text-fg-muted font-mono text-xs">
              {state.code}
              {state.message ? `: ${state.message}` : ''}
            </p>
          </div>
        )}
        {state.kind === 'cancelled' && (
          <p className="text-fg-secondary italic">
            {t('highlights.cancelled', { defaultValue: 'Generation cancelled.' })}
          </p>
        )}
      </div>
    </div>
  )
}

function formatRelativeTime(unix: number, locale: string): string {
  const now = Date.now()
  const diffSec = Math.floor((now - unix * 1000) / 1000)
  if (diffSec < 0 || diffSec < 60)
    return new Intl.RelativeTimeFormat(locale, { numeric: 'auto' }).format(0, 'minute')
  const rt = new Intl.RelativeTimeFormat(locale, { numeric: 'auto' })
  if (diffSec < 3600) return rt.format(-Math.floor(diffSec / 60), 'minute')
  if (diffSec < 86400) return rt.format(-Math.floor(diffSec / 3600), 'hour')
  if (diffSec < 86400 * 7) return rt.format(-Math.floor(diffSec / 86400), 'day')
  return new Date(unix * 1000).toLocaleDateString(locale)
}
