import init, { initSync } from './pkg/memlore_wasm'
import * as pkg from './pkg/memlore_wasm'

/** The typed memlore-wasm API (generated by `pnpm web:wasm`). */
export type Core = typeof pkg

// Vite emits the .wasm as an asset from this expression (browser); node reads it from disk.
const wasmUrl = new URL('./pkg/memlore_wasm_bg.wasm', import.meta.url)

let loading: Promise<Core> | null = null

async function initCore(): Promise<Core> {
  if (typeof window === 'undefined') {
    // Node / vitest: the --target web init() fetches by URL, which node cannot do for
    // file: URLs, so read the bytes and use initSync. The specifier is built at runtime so
    // the bundler never sees (or bundles) the node builtin.
    const fsModule = ['node', 'fs'].join(':')
    const { readFileSync } = (await import(/* @vite-ignore */ fsModule)) as typeof import('node:fs')
    initSync({ module: readFileSync(wasmUrl) })
  } else {
    await init({ module_or_path: wasmUrl })
  }
  return pkg
}

/** Load and initialise the wasm core once; every caller shares the same promise. */
export function loadCore(): Promise<Core> {
  loading ??= initCore().catch((e: unknown) => {
    loading = null
    throw e
  })
  return loading
}
