import { useEffect, useRef, useState } from 'react'
import type { CSSProperties } from 'react'
import { useTranslation } from 'react-i18next'
import { Compass, RefreshCw, X } from 'lucide-react'
import type { GoDeeperState } from '../../hooks/useGoDeeper'
import type { ReflectionLens } from '../../types/ai'
import { Button } from '../common/Button'
import { InlineOrb } from '../common/ThinkingOrb'
import { Tooltip } from '../common/Tooltip'
import { ReflectionLensPicker } from './ReflectionLensPicker'

/// Icon-only button override — square hit-target so hover background is symmetric.
const iconButtonStyle: CSSProperties = { width: 28, padding: 0 }

interface GoDeeperPopoverProps {
  entryId: string
  state: GoDeeperState
  generate: (entryId: string, lens?: ReflectionLens) => Promise<void> | void
  dismiss: () => void
  onUsePrompt: (prompt: string) => void
  onClose: () => void
}

/**
 * Go Deeper popover (replaces the inline button + card stack under
 * the editor). Auto-fires `generate(entryId)` on first open if there
 * are no prompts yet. State lives on the parent's `useGoDeeper` hook,
 * so closing & reopening shows the same prompt list.
 */
export function GoDeeperPopover({
  entryId,
  state,
  generate,
  dismiss,
  onUsePrompt,
  onClose,
}: GoDeeperPopoverProps) {
  const { t } = useTranslation('ai')
  const [lens, setLens] = useState<ReflectionLens>('default')

  const autoGeneratedRef = useRef(false)
  useEffect(() => {
    if (autoGeneratedRef.current) return
    if (state.kind === 'idle' || (state.kind === 'error' && state.entryId === entryId)) {
      autoGeneratedRef.current = true
      void generate(entryId, lens)
    }
  }, [state, generate, entryId])

  function handleUse(prompt: string) {
    onUsePrompt(prompt)
    dismiss()
    onClose()
  }

  return (
    <div
      role="dialog"
      aria-label={t('go_deeper.cards_label', { defaultValue: 'Reflection prompts' })}
      data-testid="go-deeper-popover"
      className="border-border-default bg-elevated flex max-h-[60vh] w-95 flex-col rounded-xl border shadow-lg"
    >
      <header className="border-border-default flex items-center gap-2 border-b px-3 py-2">
        <Compass className="text-accent size-4 shrink-0" aria-hidden />
        <span className="text-fg text-sm font-medium">{t('go_deeper.button')}</span>
        {state.kind === 'loading' && <InlineOrb state="searching" aria-hidden />}
        <span className="ml-auto inline-flex items-center gap-1">
          {state.kind === 'done' && (
            <Tooltip content={t('go_deeper.regenerate', { defaultValue: 'Regenerate' })}>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => void generate(entryId, lens)}
                aria-label={t('go_deeper.regenerate', { defaultValue: 'Regenerate' })}
                style={iconButtonStyle}
                className="justify-center"
              >
                <RefreshCw className="size-3.5" aria-hidden />
              </Button>
            </Tooltip>
          )}
          <Tooltip content={t('go_deeper.close', { defaultValue: 'Close' })}>
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              aria-label={t('go_deeper.close', { defaultValue: 'Close' })}
              style={iconButtonStyle}
              className="justify-center"
            >
              <X className="size-3.5" aria-hidden />
            </Button>
          </Tooltip>
        </span>
      </header>

      <div className="border-border-default border-b px-3 py-2">
        <ReflectionLensPicker
          lens={lens}
          onChange={(next) => {
            setLens(next)
            autoGeneratedRef.current = true
            void generate(entryId, next)
          }}
          compact
        />
      </div>

      <div className="flex-1 overflow-y-auto px-3 py-3 text-sm">
        {state.kind === 'idle' && (
          <p className="text-fg-secondary italic">{t('go_deeper.loading')}</p>
        )}
        {state.kind === 'loading' && (
          <p className="text-fg-secondary italic">{t('go_deeper.loading')}</p>
        )}
        {state.kind === 'error' && (
          <div className="text-danger-text space-y-1">
            <p>{t('go_deeper.error_unknown')}</p>
            <p className="text-fg-muted font-mono text-xs">{state.code}</p>
          </div>
        )}
        {state.kind === 'done' && (
          <div className="flex flex-col gap-2" role="list">
            {state.prompts.map((prompt, idx) => (
              <article
                key={idx}
                role="listitem"
                className="border-border-default bg-panel-1 flex items-start gap-3 rounded-lg border px-3 py-2.5"
              >
                <Compass className="text-accent mt-0.5 size-4 shrink-0" aria-hidden />
                <p className="text-fg flex-1 text-sm leading-relaxed">{prompt}</p>
                <Button variant="secondary" size="sm" onClick={() => handleUse(prompt)}>
                  {t('go_deeper.use_prompt')}
                </Button>
              </article>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
