// Generates src-tauri/crates/memlore-core/fixtures/web-envelopes.v1.json: a V2 media
// envelope, a thumbnail and an entry envelope, all sealed by the WASM build with the
// desktop-vault fixture's keys. A native test (`golden_web_envelopes`) opens them.
// Imports the test pkg directly (node ESM needs the .js extension). Run via `pnpm web:fixture:envelopes` (builds the test package first). Node only,
// erasable TypeScript (node --experimental-strip-types).
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import * as core from '../src/core/pkg-test/memlore_wasm.js'

const fixturesDir = new URL('../../src-tauri/crates/memlore-core/fixtures/', import.meta.url)
const outPath = fileURLToPath(new URL('web-envelopes.v1.json', fixturesDir))
const vaultPath = fileURLToPath(new URL('desktop-vault.v1.json', fixturesDir))

if (process.argv.includes('--outbox')) {
  await import('./gen-web-outbox-fixture.ts')
  process.exit(0)
}

if (existsSync(outPath) && process.env.MEMLORE_REGEN_FIXTURES !== '1') {
  console.error(
    `Refusing to overwrite ${outPath}: it is a frozen cross-language oracle.\n` +
      'If a deliberate, reviewed fixture change is really needed, run:\n' +
      '  MEMLORE_REGEN_FIXTURES=1 pnpm web:fixture:envelopes',
  )
  process.exit(1)
}

interface Vault {
  files: Record<string, string>
  recovery_phrase: string
}

const vault = JSON.parse(readFileSync(vaultPath, 'utf8')) as Vault
const text = (path: string): string => Buffer.from(vault.files[path], 'base64').toString('utf8')
const recovery = JSON.parse(text('.meta/keyring/_recovery.json')) as { wrapped_master: string }
const meta = JSON.parse(text('.meta/keyring/_meta.json')) as { master_fingerprint: string }

core.initSync({
  module: readFileSync(new URL('../src/core/pkg-test/memlore_wasm_bg.wasm', import.meta.url)),
})
const ring = core.KeyRing.fromRecovery(
  vault.recovery_phrase,
  recovery.wrapped_master,
  meta.master_fingerprint,
)
ring.loadContentList(text('.meta/keyring/_content.json'))

// Deterministic plaintexts; only the AES nonces are random.
const mediaPlain = Uint8Array.from({ length: 300 }, (_, i) => (i * 7 + 3) % 256)
const thumbPlain = Uint8Array.from([0xff, 0xd8, 0xff, 0xe0, 1, 2, 3, 4, 5, 6, 7, 8, 0xff, 0xd9])
const entryMeta = {
  entry_id: 'web-envelope-entry-1',
  title: 'Sealed by WASM',
  content_text: 'Hello from the web envelope',
}
const entryYjs = Uint8Array.from({ length: 64 }, (_, i) => (i * 13 + 5) % 256)

const b64 = (b: Uint8Array): string => Buffer.from(b).toString('base64')

const out = {
  _comment:
    'Generated by `pnpm web:fixture:envelopes` (WASM sealers, keys of desktop-vault.v1.json). ' +
    'FROZEN cross-language oracle: never regenerate casually, fix the code instead. ' +
    'Phase 14.3 `web:fixture:outbox` is a separate script; the two never regenerate each other.',
  vault_fixture: 'desktop-vault.v1.json',
  entry: {
    envelope_b64: b64(ring_seal_entry()),
    expected_metadata_json: JSON.stringify(entryMeta),
    expected_yjs_b64: b64(entryYjs),
  },
  media: {
    envelope_b64: b64(core.sealOutboxMedia(ring, mediaPlain)),
    expected_b64: b64(mediaPlain),
  },
  thumb: {
    envelope_b64: b64(core.sealOutboxThumb(ring, thumbPlain)),
    expected_b64: b64(thumbPlain),
  },
}

function ring_seal_entry(): Uint8Array {
  return core.sealEntry(ring, JSON.stringify(entryMeta), entryYjs)
}

writeFileSync(outPath, `${JSON.stringify(out, null, 2)}\n`)
ring.lock()
console.log(`wrote ${outPath}`)
