//! Master-key rotation engine for the V2 keyring.
//!
//! # State machine
//!
//! ```text
//! enumerate → reencrypt → commit_local → enumerate_stragglers → publish_keyring → done
//!                                                                                ↘ aborted
//! ```
//!
//! Each state transition is a single DB write to `rotation_job.state`. On
//! startup, `resume_rotation_if_any` finds any in-progress job via
//! `find_active_rotation_job` and drives it forward from the recorded state.
//!
//! # Crash safety
//!
//! Before leaving the `enumerate` state both the old and the new master keys
//! are wrapped with the device password and persisted locally as
//! `rotation_master_old_wrapped_local` and `rotation_master_new_wrapped_local`.
//! This means crash-resume only requires the device password until
//! `publish_keyring` time — the 24-word mnemonic is only needed when writing
//! `_recovery.json`.
//!
//! # Security decisions
//!
//! **Device password at rotation start (Option A from the plan).**  Both
//! `revoke_device` and `rotate_master_key` prompt for the current password AND
//! the 24-word recovery phrase.  The password is needed to re-wrap
//! `master_key_new` into this device's **local** unlock material (the boot
//! file / settings `wrapped_encryption_key`, see `commit_local_inner`) and to
//! verify the caller via `verify_password_hash`; the phrase is needed to write
//! a fresh `_recovery.json`.  It is **not** used for any cloud wrap — cloud
//! device slots carry no key material at all (Phase 2 de-grind).  Without both
//! we would either lose the recovery property or be unable to re-key this
//! device locally.

pub mod commit;
pub mod enumerate;
pub mod publish;
pub mod reencrypt;
pub mod rotate;

use zeroize::Zeroizing;

use crate::db;
use crate::AppState;

// Re-export the entry points callers need.
pub use commit::commit_local;
pub use enumerate::{enumerate_envelopes, enumerate_stragglers};
pub use publish::publish_keyring;
pub use reencrypt::reencrypt_items;

/// Selects where `publish_keyring` should read the recovery mnemonic from.
///
/// - **Rotate**: the mnemonic was generated by `enumerate_envelopes` and
///   stashed in the DB (`ROTATION_NEW_RECOVERY_MNEMONIC_STASH`). `publish_keyring`
///   reads and validates it internally; no user-supplied phrase is needed.
/// - **Revoke**: the caller already validated the user's phrase and holds the
///   `Mnemonic`. Pass a reference so `publish_keyring` can derive the recovery key.
pub enum RecoverySource<'a> {
    /// Rotate path — read the stashed mnemonic from the DB.
    Stashed,
    /// Revoke path — use the caller-supplied, pre-validated mnemonic.
    Supplied(&'a bip39::Mnemonic),
}

/// All key material held for the duration of one rotation job.
///
/// Both fields are `Zeroizing` so the backing memory is wiped on drop —
/// whether the job completes normally or is aborted by a panic.
/// `Zeroizing` does not implement `Debug` (intentionally — leaking key material
/// in debug output is a security risk). The struct therefore does not derive
/// `Debug`.
pub struct RotationContext {
    /// The pre-rotation master key.  Decryption uses `derive_sync_key(old)`.
    pub master_key_old: Zeroizing<[u8; 32]>,
    /// The freshly-generated post-rotation master key.  Encryption uses
    /// `derive_sync_key(new)`.
    pub master_key_new: Zeroizing<[u8; 32]>,
}

/// State values stored in `rotation_job.state` (must match DB CHECK constraint).
pub mod state {
    pub const ENUMERATE: &str = "enumerate";
    pub const REENCRYPT: &str = "reencrypt";
    pub const COMMIT_LOCAL: &str = "commit_local";
    pub const ENUMERATE_STRAGGLERS: &str = "enumerate_stragglers";
    pub const PUBLISH_KEYRING: &str = "publish_keyring";
    pub const DONE: &str = "done";
    pub const ABORTED: &str = "aborted";
}

/// Stash format: `<kek_salt_hex>:<wrapped_key_hex>` (salt is 32 hex chars = 16 bytes).
pub(crate) fn wrap_rotation_stash(master_key: &[u8; 32], password: &str) -> Result<String, String> {
    use crate::utils::encryption::generate_encryption_salt;
    let salt = generate_encryption_salt();
    let salt_hex = hex::encode(&salt);
    let wrapped_hex = crate::utils::encryption::wrap_key(master_key, password, &salt)?;
    Ok(format!("{salt_hex}:{wrapped_hex}"))
}

/// Unwrap a stash string produced by `wrap_rotation_stash`.
pub(crate) fn unwrap_rotation_stash(
    stash: &str,
    password: &str,
) -> Result<Zeroizing<[u8; 32]>, String> {
    let (salt_hex, wrapped_hex) = stash
        .split_once(':')
        .ok_or_else(|| "Invalid rotation stash format (missing ':' delimiter)".to_string())?;
    let salt =
        hex::decode(salt_hex).map_err(|e| format!("Invalid rotation stash salt hex: {e}"))?;
    let master = crate::utils::encryption::unwrap_key(wrapped_hex, password, &salt)?;
    Ok(master)
}

/// Reconstruct both master keys from the locally-stashed wrapped values.
///
/// Only needs the device password (no mnemonic required until `publish_keyring`).
pub fn reconstruct_keys_from_stash(
    state: &AppState,
    current_password: &str,
) -> Result<(Zeroizing<[u8; 32]>, Zeroizing<[u8; 32]>), String> {
    let conn = state.lock()?;

    let old_wrapped = db::get_setting(&conn, db::ROTATION_MASTER_OLD_WRAPPED_LOCAL)
        .map_err(|e| e.to_string())?
        .ok_or_else(|| {
            "No stashed old master key found — cannot resume rotation without \
             re-entering the original password."
                .to_string()
        })?;

    let new_wrapped = db::get_setting(&conn, db::ROTATION_MASTER_NEW_WRAPPED_LOCAL)
        .map_err(|e| e.to_string())?
        .ok_or_else(|| {
            "No stashed new master key found — cannot resume rotation without \
             re-entering the original password."
                .to_string()
        })?;

    let master_key_old = unwrap_rotation_stash(&old_wrapped, current_password)?;
    let master_key_new = unwrap_rotation_stash(&new_wrapped, current_password)?;

    Ok((master_key_old, master_key_new))
}

/// Discard a rotation job that is a pre-publication orphan with no stash material.
///
/// A job is discardable ONLY when BOTH conditions hold:
/// (a) Its state is a **pre-publication** state — `enumerate`, `reencrypt`, or
///     `commit_local` — meaning no cloud writes have occurred yet.
/// (b) The master-key stashes (ROTATION_MASTER_OLD/NEW_WRAPPED_LOCAL) are absent,
///     making the job permanently unresumable.
///
/// Jobs in `enumerate_stragglers` or `publish_keyring` state are NEVER discarded
/// here, regardless of whether their master-key stashes are present.  A job that
/// reached those states may have already published `_recovery.json` and
/// `_meta.json` to the cloud (the cloud write IS publication).  Discarding such a
/// job — and especially clearing the recovery mnemonic stash — would delete the
/// only local copy of an already-published live recovery phrase, causing permanent
/// multi-device lockout.  Such jobs must be routed to `resume_rotation` instead.
///
/// Returns `true` if a job was found and discarded, `false` if no active job
/// exists or if the job must be left intact for resume.
pub fn discard_orphaned_rotation_job_if_any(state: &AppState) -> Result<bool, String> {
    let conn = state.lock()?;

    let job = match db::find_active_rotation_job(&conn).map_err(|e| e.to_string())? {
        Some(j) => j,
        None => return Ok(false),
    };

    // Never discard a job that has already reached or passed the publication
    // boundary.  These states require resume, not discard.
    let is_pre_publication = matches!(
        job.state.as_str(),
        state::ENUMERATE | state::REENCRYPT | state::COMMIT_LOCAL
    );
    if !is_pre_publication {
        log::debug!(
            "discard_orphaned_rotation_job_if_any: job {} is in post-publication state '{}' \
             — leaving intact for resume",
            job.id,
            job.state
        );
        return Ok(false);
    }

    let has_old_stash = db::get_setting(&conn, db::ROTATION_MASTER_OLD_WRAPPED_LOCAL)
        .map_err(|e| e.to_string())?
        .is_some();
    let has_new_stash = db::get_setting(&conn, db::ROTATION_MASTER_NEW_WRAPPED_LOCAL)
        .map_err(|e| e.to_string())?
        .is_some();

    if has_old_stash && has_new_stash {
        // Stash is intact — this job can be resumed; don't discard it.
        return Ok(false);
    }

    log::warn!(
        "discard_orphaned_rotation_job_if_any: job {} (state='{}') has no stash — \
         discarding unresumable pre-publication job",
        job.id,
        job.state
    );

    db::update_rotation_job_state(&conn, job.id, state::ABORTED).map_err(|e| e.to_string())?;
    // Clear any partial stash entries so there is no leftover garbage.
    let _ = db::delete_setting(&conn, db::ROTATION_MASTER_OLD_WRAPPED_LOCAL);
    let _ = db::delete_setting(&conn, db::ROTATION_MASTER_NEW_WRAPPED_LOCAL);
    // NOTE: Do NOT clear the recovery mnemonic stash here.  If a published job
    // somehow reached this path (it shouldn't — the pre-publication guard above
    // prevents it), clearing the stash would delete the only copy of a live
    // recovery phrase.  The positive gate in get_pending_rotation_recovery /
    // confirm_rotation_recovery_saved (state == done) is the authoritative guard.

    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;
    use crate::db::schema::migrate;
    use rusqlite::Connection;

    fn setup_db() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        migrate(&conn).unwrap();
        conn
    }

    /// C3: An active rotation job that has no stash entries (ROTATION_MASTER_OLD/NEW_WRAPPED_LOCAL)
    /// must be discarded cleanly — marked `aborted`, no panic, no infinite loop.
    #[test]
    fn discard_orphaned_job_with_no_stash() {
        let conn = setup_db();
        // Insert an active job (in `enumerate` state — no cloud mutations occurred).
        let id = db::insert_rotation_job(&conn, "fp-old", "fp-new", 1, 2, None).unwrap();
        // Do NOT write any stash entries — simulates a crash before the stash write
        // (impossible after the C3 fix but still the defensive path).
        assert!(
            db::get_setting(&conn, db::ROTATION_MASTER_OLD_WRAPPED_LOCAL)
                .unwrap()
                .is_none()
        );

        let app_state = AppState::new(conn);
        let discarded = discard_orphaned_rotation_job_if_any(&app_state).unwrap();
        assert!(discarded, "expected the orphaned job to be discarded");

        let conn = app_state.lock().unwrap();
        let job = db::find_active_rotation_job(&conn).unwrap();
        assert!(job.is_none(), "active job should be gone after discard");

        // The row itself should exist but be in `aborted` state.
        let state_val: String = conn
            .query_row("SELECT state FROM rotation_job WHERE id=?1", [id], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(state_val, "aborted");
    }

    /// C3: When stash IS present, `discard_orphaned_rotation_job_if_any` returns false
    /// and leaves the job untouched.
    #[test]
    fn discard_orphaned_job_leaves_intact_when_stash_present() {
        let conn = setup_db();
        let _id = db::insert_rotation_job(&conn, "fp-old", "fp-new", 1, 2, None).unwrap();
        // Write both stash entries.
        db::set_setting(
            &conn,
            db::ROTATION_MASTER_OLD_WRAPPED_LOCAL,
            "dummy_old_stash",
        )
        .unwrap();
        db::set_setting(
            &conn,
            db::ROTATION_MASTER_NEW_WRAPPED_LOCAL,
            "dummy_new_stash",
        )
        .unwrap();

        let app_state = AppState::new(conn);
        let discarded = discard_orphaned_rotation_job_if_any(&app_state).unwrap();
        assert!(!discarded, "should NOT discard a job that has a stash");

        // Job must still be active.
        let conn = app_state.lock().unwrap();
        let job = db::find_active_rotation_job(&conn).unwrap();
        assert!(job.is_some(), "job should still be active");
    }

    /// C3: When there is no active job, `discard_orphaned_rotation_job_if_any` returns false
    /// without error.
    #[test]
    fn discard_orphaned_job_no_op_when_no_active_job() {
        let conn = setup_db();
        let app_state = AppState::new(conn);
        let result = discard_orphaned_rotation_job_if_any(&app_state).unwrap();
        assert!(!result);
    }

    /// Change 2: A job in `publish_keyring` state with missing master-key stash must
    /// NOT be discarded — it may have already published to the cloud.  The function
    /// must return `false` and leave the job intact (not set `aborted`).
    /// If a recovery mnemonic stash exists it must be preserved.
    #[test]
    fn discard_orphaned_does_not_discard_publish_keyring_job() {
        let conn = setup_db();
        // Insert a job and advance it to publish_keyring (post-publication boundary).
        let id = db::insert_rotation_job(&conn, "fp-old", "fp-new", 1, 2, None).unwrap();
        db::update_rotation_job_state(&conn, id, state::PUBLISH_KEYRING).unwrap();

        // Stash a recovery mnemonic (the live phrase from a published rotation).
        db::set_rotation_recovery_stash(&conn, "word1 word2 word3").unwrap();

        // Do NOT write master-key stashes (simulates crash after step 7).
        let app_state = AppState::new(conn);
        let discarded = discard_orphaned_rotation_job_if_any(&app_state).unwrap();
        assert!(
            !discarded,
            "publish_keyring job must NOT be discarded — it may be published"
        );

        let conn = app_state.lock().unwrap();
        // Job must still be active (state != aborted).
        let job = db::find_active_rotation_job(&conn).unwrap();
        assert!(
            job.is_some(),
            "job should still be active after discard_orphaned on a publish_keyring state"
        );
        let state_val: String = conn
            .query_row("SELECT state FROM rotation_job WHERE id=?1", [id], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(state_val, state::PUBLISH_KEYRING, "state must not change");

        // Recovery mnemonic stash must be intact.
        let stash = db::get_rotation_recovery_stash(&conn).unwrap();
        assert_eq!(
            stash.as_deref(),
            Some("word1 word2 word3"),
            "recovery stash must be preserved when publish_keyring job is left intact"
        );
    }

    /// Change 2: A job in a pre-publication state (`enumerate`) with missing stash
    /// is still discarded as before — the existing behavior must be preserved.
    #[test]
    fn discard_orphaned_still_discards_enumerate_job() {
        let conn = setup_db();
        // `enumerate` is the default initial state from insert_rotation_job.
        let id = db::insert_rotation_job(&conn, "fp-old", "fp-new", 1, 2, None).unwrap();

        // Verify initial state is `enumerate`.
        let initial: String = conn
            .query_row("SELECT state FROM rotation_job WHERE id=?1", [id], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(initial, state::ENUMERATE);

        // No stash — simulates crash before stash write in enumerate_envelopes.
        let app_state = AppState::new(conn);
        let discarded = discard_orphaned_rotation_job_if_any(&app_state).unwrap();
        assert!(discarded, "enumerate job with no stash must be discarded");

        let conn = app_state.lock().unwrap();
        let active = db::find_active_rotation_job(&conn).unwrap();
        assert!(active.is_none(), "job should be aborted after discard");

        let state_val: String = conn
            .query_row("SELECT state FROM rotation_job WHERE id=?1", [id], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(state_val, state::ABORTED);
    }
}
