// Curated emoji catalog grouped by category. Each entry: [emoji, keywords for search].
// Kept compact (no full Unicode dependency) but broad enough to feel "complete" as a picker.

export interface EmojiEntry {
  char: string
  keywords: string
}

export interface EmojiCategory {
  id: string
  /** Default English label. Category metadata (label/labelKey/icon) is
   *  currently unused — the journal emoji picker that rendered it was
   *  removed; only `emojis` is read (via ALL_EMOJIS) by the editor
   *  `:shortcode:` feature. Retained with the catalog for potential reuse. */
  label: string
  labelKey: string
  icon: string
  emojis: EmojiEntry[]
}

const e = (char: string, keywords: string): EmojiEntry => ({ char, keywords })

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & People',
    labelKey: 'smileys',
    icon: '😀',
    emojis: [
      e('😀', 'grinning face happy smile'),
      e('😃', 'smile happy joy'),
      e('😄', 'smile happy laugh'),
      e('😁', 'beam grin happy'),
      e('😆', 'laugh happy lol'),
      e('😅', 'sweat smile relief'),
      e('🤣', 'rofl laugh rolling'),
      e('😂', 'joy tears laugh cry'),
      e('🙂', 'slight smile'),
      e('🙃', 'upside down silly'),
      e('😉', 'wink flirt'),
      e('😊', 'blush happy'),
      e('😇', 'angel innocent halo'),
      e('🥰', 'love hearts adore'),
      e('😍', 'heart eyes love'),
      e('🤩', 'star struck wow'),
      e('😘', 'kiss blow'),
      e('😗', 'kiss'),
      e('😚', 'kiss closed eyes'),
      e('😋', 'yum tasty tongue'),
      e('😛', 'tongue out playful'),
      e('😜', 'wink tongue silly'),
      e('🤪', 'zany crazy silly'),
      e('🤨', 'raised eyebrow skeptical'),
      e('🧐', 'monocle thinking curious'),
      e('🤓', 'nerd glasses geek'),
      e('😎', 'cool sunglasses'),
      e('🥳', 'party celebration birthday'),
      e('😏', 'smirk knowing'),
      e('😒', 'unamused meh'),
      e('😞', 'sad disappointed'),
      e('😔', 'pensive sad'),
      e('😟', 'worried sad'),
      e('😕', 'confused unsure'),
      e('🙁', 'frown slight sad'),
      e('☹️', 'frown sad'),
      e('😣', 'persevere struggle'),
      e('😖', 'confounded frustrated'),
      e('😫', 'tired exhausted'),
      e('😩', 'weary tired'),
      e('🥺', 'pleading puppy eyes'),
      e('😢', 'cry tear sad'),
      e('😭', 'sob crying loud'),
      e('😤', 'huff angry frustrated'),
      e('😠', 'angry mad'),
      e('😡', 'pout rage furious'),
      e('🤬', 'cursing swear angry'),
      e('🤯', 'mind blown shocked'),
      e('😳', 'flushed embarrassed'),
      e('🥵', 'hot sweat heat'),
      e('🥶', 'cold freezing'),
      e('😶', 'speechless blank'),
      e('😐', 'neutral meh'),
      e('😑', 'expressionless'),
      e('🙄', 'eye roll annoyed'),
      e('😬', 'grimace awkward'),
      e('🤥', 'lying pinocchio'),
      e('😌', 'relieved calm'),
      e('😴', 'sleep zzz tired'),
      e('🤤', 'drool sleep'),
      e('😪', 'sleepy tired'),
      e('🤐', 'zipper quiet silent'),
      e('🤢', 'nausea sick disgust'),
      e('🤮', 'vomit sick'),
      e('🤧', 'sneeze sick'),
      e('😷', 'mask sick health'),
      e('🤒', 'thermometer sick fever'),
      e('🤕', 'bandage hurt injury'),
      e('🤑', 'money mouth rich'),
      e('🤠', 'cowboy hat'),
      e('🤡', 'clown'),
      e('👻', 'ghost spooky'),
      e('💀', 'skull death'),
      e('☠️', 'skull crossbones danger'),
      e('👽', 'alien space'),
      e('👾', 'invader game alien'),
      e('🤖', 'robot bot'),
      e('🎃', 'pumpkin halloween'),
      e('😺', 'cat smile happy'),
      e('😸', 'cat grin'),
      e('😹', 'cat joy tears'),
      e('😻', 'cat heart eyes'),
      e('😼', 'cat smirk'),
      e('😽', 'cat kiss'),
      e('🙀', 'cat scream'),
      e('😿', 'cat cry'),
      e('😾', 'cat pout'),
      e('🙈', 'monkey see no evil'),
      e('🙉', 'monkey hear no evil'),
      e('🙊', 'monkey speak no evil'),
      e('💋', 'kiss mark lipstick'),
      e('💌', 'love letter heart'),
      e('💘', 'heart arrow cupid'),
      e('💝', 'heart gift'),
      e('💖', 'sparkling heart'),
      e('💗', 'growing heart'),
      e('💓', 'beating heart'),
      e('💞', 'revolving hearts'),
      e('💕', 'two hearts'),
      e('💟', 'heart decoration'),
      e('❣️', 'heart exclamation'),
      e('💔', 'broken heart'),
      e('❤️', 'red heart love'),
      e('🧡', 'orange heart'),
      e('💛', 'yellow heart'),
      e('💚', 'green heart'),
      e('💙', 'blue heart'),
      e('💜', 'purple heart'),
      e('🤎', 'brown heart'),
      e('🖤', 'black heart'),
      e('🤍', 'white heart'),
      e('💯', '100 hundred perfect'),
      e('💢', 'anger symbol'),
      e('💥', 'collision boom'),
      e('💫', 'dizzy stars'),
      e('💦', 'sweat droplets water'),
      e('💨', 'dash wind fast'),
      e('🕳️', 'hole'),
      e('💣', 'bomb'),
      e('💬', 'speech bubble'),
      e('💭', 'thought bubble'),
      e('💤', 'zzz sleep'),
      e('👋', 'wave hello hi bye'),
      e('🤚', 'raised back of hand stop'),
      e('🖐️', 'hand fingers splayed'),
      e('✋', 'raised hand high five'),
      e('🖖', 'vulcan spock'),
      e('👌', 'ok perfect'),
      e('🤏', 'pinch small'),
      e('✌️', 'peace victory'),
      e('🤞', 'fingers crossed luck'),
      e('🤟', 'love you sign'),
      e('🤘', 'rock on horns'),
      e('🤙', 'call me shaka'),
      e('👈', 'point left'),
      e('👉', 'point right'),
      e('👆', 'point up'),
      e('🖕', 'middle finger'),
      e('👇', 'point down'),
      e('☝️', 'index up'),
      e('👍', 'thumbs up like yes'),
      e('👎', 'thumbs down dislike no'),
      e('✊', 'fist raised'),
      e('👊', 'fist bump punch'),
      e('🤛', 'fist left'),
      e('🤜', 'fist right'),
      e('👏', 'clap applause'),
      e('🙌', 'raised hands praise celebrate'),
      e('👐', 'open hands hug'),
      e('🤲', 'palms up together prayer'),
      e('🤝', 'handshake deal'),
      e('🙏', 'pray thanks please'),
      e('💪', 'muscle strong flex'),
      e('🦾', 'mechanical arm prosthetic'),
      e('🦿', 'mechanical leg prosthetic'),
      e('🦵', 'leg'),
      e('🦶', 'foot'),
      e('👂', 'ear listen'),
      e('🦻', 'ear hearing aid'),
      e('👃', 'nose smell'),
      e('🧠', 'brain mind smart think'),
      e('🫀', 'anatomical heart'),
      e('🫁', 'lungs breath'),
      e('🦷', 'tooth dental'),
      e('🦴', 'bone'),
      e('👀', 'eyes look see'),
      e('👁️', 'eye'),
      e('👅', 'tongue'),
      e('👄', 'mouth lips'),
      e('👶', 'baby'),
      e('🧒', 'child'),
      e('👦', 'boy'),
      e('👧', 'girl'),
      e('🧑', 'person adult'),
      e('👱', 'person blond'),
      e('👨', 'man'),
      e('🧔', 'beard'),
      e('👩', 'woman'),
      e('🧓', 'older person'),
      e('👴', 'old man'),
      e('👵', 'old woman'),
      e('🙍', 'frowning person'),
      e('🙎', 'pouting person'),
      e('🙅', 'no gesture'),
      e('🙆', 'ok gesture'),
      e('💁', 'tipping hand info'),
      e('🙋', 'raising hand'),
      e('🧏', 'deaf person'),
      e('🙇', 'bow apologize'),
      e('🤦', 'facepalm'),
      e('🤷', 'shrug'),
      e('👮', 'police officer cop'),
      e('🕵️', 'detective spy'),
      e('💂', 'guard'),
      e('🥷', 'ninja'),
      e('👷', 'construction worker'),
      e('🤴', 'prince'),
      e('👸', 'princess'),
      e('👳', 'turban'),
      e('👲', 'cap person'),
      e('🧕', 'headscarf'),
      e('🤵', 'tuxedo wedding'),
      e('👰', 'bride wedding'),
      e('🤰', 'pregnant'),
      e('🤱', 'breastfeeding'),
      e('👼', 'baby angel'),
      e('🎅', 'santa claus'),
      e('🤶', 'mrs claus'),
      e('🦸', 'superhero'),
      e('🦹', 'supervillain'),
      e('🧙', 'mage wizard'),
      e('🧚', 'fairy'),
      e('🧛', 'vampire'),
      e('🧜', 'merperson'),
      e('🧝', 'elf'),
      e('🧞', 'genie'),
      e('🧟', 'zombie'),
      e('💆', 'face massage spa'),
      e('💇', 'haircut barber'),
      e('🚶', 'walking pedestrian'),
      e('🧍', 'standing'),
      e('🧎', 'kneeling'),
      e('🏃', 'running jog'),
      e('💃', 'dancer woman'),
      e('🕺', 'dancer man'),
      e('🕴️', 'business suit levitating'),
      e('👯', 'dancers'),
      e('🧖', 'sauna spa'),
      e('🧗', 'climbing'),
      e('🤺', 'fencing'),
      e('🏇', 'horse racing'),
      e('⛷️', 'skier'),
      e('🏂', 'snowboarder'),
      e('🏌️', 'golfer'),
      e('🏄', 'surfer'),
      e('🚣', 'rowboat'),
      e('🏊', 'swimming'),
      e('⛹️', 'bouncing ball'),
      e('🏋️', 'weight lifting'),
      e('🚴', 'cycling bike'),
      e('🚵', 'mountain biking'),
      e('🤸', 'cartwheel'),
      e('🤼', 'wrestling'),
      e('🤽', 'water polo'),
      e('🤾', 'handball'),
      e('🤹', 'juggling'),
      e('🧘', 'lotus meditation yoga'),
      e('🛀', 'bath'),
      e('🛌', 'sleeping bed'),
    ],
  },
  {
    id: 'animals',
    label: 'Animals & Nature',
    labelKey: 'animals',
    icon: '🐾',
    emojis: [
      e('🐶', 'dog puppy'),
      e('🐱', 'cat kitten'),
      e('🐭', 'mouse'),
      e('🐹', 'hamster'),
      e('🐰', 'rabbit bunny'),
      e('🦊', 'fox'),
      e('🐻', 'bear'),
      e('🐼', 'panda'),
      e('🐻‍❄️', 'polar bear'),
      e('🐨', 'koala'),
      e('🐯', 'tiger'),
      e('🦁', 'lion'),
      e('🐮', 'cow'),
      e('🐷', 'pig'),
      e('🐽', 'pig nose'),
      e('🐸', 'frog'),
      e('🐵', 'monkey'),
      e('🙈', 'see no evil monkey'),
      e('🙉', 'hear no evil monkey'),
      e('🙊', 'speak no evil monkey'),
      e('🐒', 'monkey'),
      e('🐔', 'chicken'),
      e('🐧', 'penguin'),
      e('🐦', 'bird'),
      e('🐤', 'baby chick'),
      e('🐣', 'hatching chick'),
      e('🐥', 'front chick'),
      e('🦆', 'duck'),
      e('🦅', 'eagle'),
      e('🦉', 'owl'),
      e('🦇', 'bat'),
      e('🐺', 'wolf'),
      e('🐗', 'boar'),
      e('🐴', 'horse'),
      e('🦄', 'unicorn'),
      e('🐝', 'bee honey'),
      e('🐛', 'bug caterpillar'),
      e('🦋', 'butterfly'),
      e('🐌', 'snail'),
      e('🐞', 'ladybug'),
      e('🐜', 'ant'),
      e('🦟', 'mosquito'),
      e('🦗', 'cricket'),
      e('🕷️', 'spider'),
      e('🦂', 'scorpion'),
      e('🐢', 'turtle'),
      e('🐍', 'snake'),
      e('🦎', 'lizard'),
      e('🦖', 't rex dinosaur'),
      e('🦕', 'sauropod dinosaur'),
      e('🐙', 'octopus'),
      e('🦑', 'squid'),
      e('🦐', 'shrimp'),
      e('🦞', 'lobster'),
      e('🦀', 'crab'),
      e('🐡', 'blowfish'),
      e('🐠', 'tropical fish'),
      e('🐟', 'fish'),
      e('🐬', 'dolphin'),
      e('🐳', 'whale'),
      e('🐋', 'whale'),
      e('🦈', 'shark'),
      e('🐊', 'crocodile'),
      e('🐅', 'tiger'),
      e('🐆', 'leopard'),
      e('🦓', 'zebra'),
      e('🦍', 'gorilla'),
      e('🦧', 'orangutan'),
      e('🐘', 'elephant'),
      e('🦛', 'hippopotamus'),
      e('🦏', 'rhino'),
      e('🐪', 'camel'),
      e('🐫', 'two-hump camel'),
      e('🦒', 'giraffe'),
      e('🦘', 'kangaroo'),
      e('🐃', 'buffalo'),
      e('🐂', 'ox'),
      e('🐄', 'cow'),
      e('🐎', 'horse'),
      e('🐖', 'pig'),
      e('🐏', 'ram'),
      e('🐑', 'sheep'),
      e('🦙', 'llama'),
      e('🐐', 'goat'),
      e('🦌', 'deer'),
      e('🐕', 'dog'),
      e('🐩', 'poodle'),
      e('🦮', 'guide dog'),
      e('🐈', 'cat'),
      e('🐓', 'rooster'),
      e('🦃', 'turkey'),
      e('🦚', 'peacock'),
      e('🦜', 'parrot'),
      e('🦢', 'swan'),
      e('🦩', 'flamingo'),
      e('🕊️', 'dove peace'),
      e('🐇', 'rabbit'),
      e('🦝', 'raccoon'),
      e('🦨', 'skunk'),
      e('🦡', 'badger'),
      e('🦦', 'otter'),
      e('🦥', 'sloth'),
      e('🐁', 'mouse'),
      e('🐀', 'rat'),
      e('🐿️', 'chipmunk'),
      e('🦔', 'hedgehog'),
      e('🐾', 'paw prints'),
      e('🐉', 'dragon'),
      e('🐲', 'dragon face'),
      e('🌵', 'cactus'),
      e('🎄', 'christmas tree'),
      e('🌲', 'evergreen tree'),
      e('🌳', 'deciduous tree'),
      e('🌴', 'palm tree'),
      e('🌱', 'seedling sprout'),
      e('🌿', 'herb'),
      e('☘️', 'shamrock'),
      e('🍀', 'four leaf clover luck'),
      e('🎍', 'pine decoration'),
      e('🎋', 'tanabata tree'),
      e('🍃', 'leaves wind'),
      e('🍂', 'fallen leaf autumn'),
      e('🍁', 'maple leaf'),
      e('🌾', 'sheaf of rice'),
      e('🌺', 'hibiscus'),
      e('🌻', 'sunflower'),
      e('🌹', 'rose'),
      e('🥀', 'wilted flower'),
      e('🌷', 'tulip'),
      e('🌸', 'cherry blossom'),
      e('💐', 'bouquet flowers'),
      e('🌼', 'blossom'),
      e('🌎', 'earth americas'),
      e('🌍', 'earth africa europe'),
      e('🌏', 'earth asia australia'),
      e('🌕', 'full moon'),
      e('🌖', 'waning gibbous'),
      e('🌗', 'last quarter moon'),
      e('🌘', 'waning crescent'),
      e('🌑', 'new moon'),
      e('🌒', 'waxing crescent'),
      e('🌓', 'first quarter moon'),
      e('🌔', 'waxing gibbous'),
      e('🌚', 'new moon face'),
      e('🌝', 'full moon face'),
      e('🌞', 'sun face'),
      e('🌛', 'first quarter moon face'),
      e('🌜', 'last quarter moon face'),
      e('🌙', 'crescent moon'),
      e('⭐', 'star'),
      e('🌟', 'glowing star sparkle'),
      e('💫', 'dizzy star'),
      e('✨', 'sparkles magic shine'),
      e('☄️', 'comet'),
      e('☀️', 'sun sunny'),
      e('🌤️', 'sun behind cloud'),
      e('⛅', 'partly cloudy'),
      e('🌥️', 'sun behind large cloud'),
      e('☁️', 'cloud cloudy'),
      e('🌦️', 'sun behind rain cloud'),
      e('🌧️', 'rain'),
      e('⛈️', 'thunder cloud rain'),
      e('🌩️', 'lightning'),
      e('🌨️', 'snow cloud'),
      e('❄️', 'snowflake cold'),
      e('☃️', 'snowman'),
      e('⛄', 'snowman no snow'),
      e('🌬️', 'wind face'),
      e('💨', 'dash'),
      e('💧', 'droplet water'),
      e('💦', 'sweat droplets'),
      e('☔', 'umbrella rain'),
      e('☂️', 'umbrella'),
      e('🌊', 'wave ocean'),
      e('🌫️', 'fog'),
      e('🌈', 'rainbow'),
      e('🔥', 'fire flame'),
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    labelKey: 'food',
    icon: '🍎',
    emojis: [
      e('🍏', 'green apple'),
      e('🍎', 'red apple'),
      e('🍐', 'pear'),
      e('🍊', 'tangerine orange'),
      e('🍋', 'lemon'),
      e('🍌', 'banana'),
      e('🍉', 'watermelon'),
      e('🍇', 'grapes'),
      e('🍓', 'strawberry'),
      e('🫐', 'blueberries'),
      e('🍈', 'melon'),
      e('🍒', 'cherries'),
      e('🍑', 'peach'),
      e('🥭', 'mango'),
      e('🍍', 'pineapple'),
      e('🥥', 'coconut'),
      e('🥝', 'kiwi'),
      e('🍅', 'tomato'),
      e('🍆', 'eggplant'),
      e('🥑', 'avocado'),
      e('🥦', 'broccoli'),
      e('🥬', 'leafy green'),
      e('🥒', 'cucumber'),
      e('🌶️', 'hot pepper chili'),
      e('🫑', 'bell pepper'),
      e('🌽', 'corn'),
      e('🥕', 'carrot'),
      e('🧄', 'garlic'),
      e('🧅', 'onion'),
      e('🥔', 'potato'),
      e('🍠', 'sweet potato'),
      e('🥐', 'croissant'),
      e('🥯', 'bagel'),
      e('🍞', 'bread'),
      e('🥖', 'baguette'),
      e('🥨', 'pretzel'),
      e('🧀', 'cheese'),
      e('🥚', 'egg'),
      e('🍳', 'cooking fried egg'),
      e('🧈', 'butter'),
      e('🥞', 'pancakes'),
      e('🧇', 'waffle'),
      e('🥓', 'bacon'),
      e('🥩', 'cut of meat steak'),
      e('🍗', 'poultry leg chicken'),
      e('🍖', 'meat on bone'),
      e('🌭', 'hot dog'),
      e('🍔', 'hamburger burger'),
      e('🍟', 'french fries'),
      e('🍕', 'pizza'),
      e('🥪', 'sandwich'),
      e('🥙', 'stuffed flatbread'),
      e('🧆', 'falafel'),
      e('🌮', 'taco'),
      e('🌯', 'burrito'),
      e('🥗', 'green salad'),
      e('🥘', 'shallow pan of food paella'),
      e('🥫', 'canned food'),
      e('🍝', 'spaghetti pasta'),
      e('🍜', 'steaming bowl ramen noodles'),
      e('🍲', 'pot of food stew'),
      e('🍛', 'curry rice'),
      e('🍣', 'sushi'),
      e('🍱', 'bento'),
      e('🥟', 'dumpling'),
      e('🦪', 'oyster'),
      e('🍤', 'fried shrimp'),
      e('🍙', 'rice ball onigiri'),
      e('🍚', 'cooked rice'),
      e('🍘', 'rice cracker'),
      e('🍥', 'fish cake'),
      e('🥠', 'fortune cookie'),
      e('🥮', 'moon cake'),
      e('🍢', 'oden'),
      e('🍡', 'dango'),
      e('🍧', 'shaved ice'),
      e('🍨', 'ice cream'),
      e('🍦', 'soft ice cream'),
      e('🥧', 'pie'),
      e('🧁', 'cupcake'),
      e('🍰', 'shortcake slice'),
      e('🎂', 'birthday cake'),
      e('🍮', 'custard flan'),
      e('🍭', 'lollipop'),
      e('🍬', 'candy'),
      e('🍫', 'chocolate bar'),
      e('🍿', 'popcorn'),
      e('🍩', 'doughnut'),
      e('🍪', 'cookie'),
      e('🌰', 'chestnut'),
      e('🥜', 'peanuts'),
      e('🍯', 'honey pot'),
      e('🥛', 'glass of milk'),
      e('🍼', 'baby bottle'),
      e('☕', 'coffee hot beverage'),
      e('🍵', 'teacup tea'),
      e('🍶', 'sake'),
      e('🍺', 'beer mug'),
      e('🍻', 'clinking beer mugs cheers'),
      e('🥂', 'clinking glasses champagne'),
      e('🍷', 'wine glass'),
      e('🥃', 'tumbler whiskey'),
      e('🍸', 'cocktail martini'),
      e('🍹', 'tropical drink'),
      e('🍾', 'bottle popping champagne'),
      e('🧊', 'ice cube'),
      e('🥄', 'spoon'),
      e('🍴', 'fork knife'),
      e('🍽️', 'fork knife plate'),
      e('🥣', 'bowl with spoon'),
      e('🥡', 'takeout box'),
      e('🥢', 'chopsticks'),
      e('🧂', 'salt'),
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    labelKey: 'activities',
    icon: '⚽',
    emojis: [
      e('⚽', 'soccer football'),
      e('🏀', 'basketball'),
      e('🏈', 'american football'),
      e('⚾', 'baseball'),
      e('🥎', 'softball'),
      e('🎾', 'tennis'),
      e('🏐', 'volleyball'),
      e('🏉', 'rugby'),
      e('🥏', 'flying disc frisbee'),
      e('🎱', '8 ball pool billiards'),
      e('🪀', 'yo-yo'),
      e('🏓', 'ping pong'),
      e('🏸', 'badminton'),
      e('🏒', 'ice hockey'),
      e('🏑', 'field hockey'),
      e('🥍', 'lacrosse'),
      e('🏏', 'cricket'),
      e('🥅', 'goal net'),
      e('⛳', 'flag in hole golf'),
      e('🪁', 'kite'),
      e('🏹', 'bow and arrow archery'),
      e('🎣', 'fishing pole'),
      e('🤿', 'diving mask'),
      e('🥊', 'boxing glove'),
      e('🥋', 'martial arts uniform'),
      e('🎽', 'running shirt'),
      e('🛹', 'skateboard'),
      e('🛷', 'sled'),
      e('⛸️', 'ice skate'),
      e('🥌', 'curling stone'),
      e('🎿', 'skis'),
      e('⛷️', 'skier'),
      e('🏂', 'snowboarder'),
      e('🪂', 'parachute'),
      e('🏋️', 'weight lifting gym'),
      e('🤼', 'wrestling'),
      e('🤸', 'cartwheel gymnastics'),
      e('⛹️', 'bouncing ball'),
      e('🤺', 'fencing'),
      e('🤾', 'handball'),
      e('🏌️', 'golfer'),
      e('🏇', 'horse racing'),
      e('🧘', 'yoga meditation'),
      e('🏄', 'surfing'),
      e('🏊', 'swimming'),
      e('🤽', 'water polo'),
      e('🚣', 'rowboat'),
      e('🧗', 'climbing'),
      e('🚵', 'mountain biking'),
      e('🚴', 'biking cycling'),
      e('🏆', 'trophy winner'),
      e('🥇', 'gold medal first'),
      e('🥈', 'silver medal second'),
      e('🥉', 'bronze medal third'),
      e('🏅', 'sports medal'),
      e('🎖️', 'military medal'),
      e('🏵️', 'rosette'),
      e('🎗️', 'reminder ribbon'),
      e('🎫', 'ticket'),
      e('🎟️', 'admission tickets'),
      e('🎪', 'circus tent'),
      e('🤹', 'juggling'),
      e('🎭', 'performing arts theater drama'),
      e('🩰', 'ballet shoes'),
      e('🎨', 'art palette painting'),
      e('🎬', 'clapper board movie'),
      e('🎤', 'microphone'),
      e('🎧', 'headphone music'),
      e('🎼', 'musical score'),
      e('🎹', 'piano keys'),
      e('🥁', 'drum'),
      e('🪘', 'long drum'),
      e('🎷', 'saxophone'),
      e('🎺', 'trumpet'),
      e('🪗', 'accordion'),
      e('🎸', 'guitar'),
      e('🪕', 'banjo'),
      e('🎻', 'violin'),
      e('🎲', 'game die dice'),
      e('♟️', 'chess pawn'),
      e('🎯', 'darts bullseye target'),
      e('🎳', 'bowling'),
      e('🎮', 'video game controller'),
      e('🕹️', 'joystick'),
      e('🎰', 'slot machine'),
      e('🧩', 'puzzle piece'),
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    labelKey: 'travel',
    icon: '🚗',
    emojis: [
      e('🚗', 'car automobile'),
      e('🚕', 'taxi'),
      e('🚙', 'suv sport utility'),
      e('🚌', 'bus'),
      e('🚎', 'trolleybus'),
      e('🏎️', 'racing car'),
      e('🚓', 'police car'),
      e('🚑', 'ambulance'),
      e('🚒', 'fire engine'),
      e('🚐', 'minibus'),
      e('🛻', 'pickup truck'),
      e('🚚', 'delivery truck'),
      e('🚛', 'articulated lorry'),
      e('🚜', 'tractor'),
      e('🦯', 'white cane'),
      e('🦽', 'manual wheelchair'),
      e('🦼', 'motorized wheelchair'),
      e('🛴', 'kick scooter'),
      e('🚲', 'bicycle bike'),
      e('🛵', 'motor scooter moped'),
      e('🏍️', 'motorcycle'),
      e('🛺', 'auto rickshaw'),
      e('🚨', 'police light siren'),
      e('🚔', 'oncoming police car'),
      e('🚍', 'oncoming bus'),
      e('🚘', 'oncoming car'),
      e('🚖', 'oncoming taxi'),
      e('🚡', 'aerial tramway'),
      e('🚠', 'mountain cableway'),
      e('🚟', 'suspension railway'),
      e('🚃', 'railway car'),
      e('🚋', 'tram car'),
      e('🚞', 'mountain railway'),
      e('🚝', 'monorail'),
      e('🚄', 'high speed train'),
      e('🚅', 'bullet train'),
      e('🚈', 'light rail'),
      e('🚂', 'locomotive steam'),
      e('🚆', 'train'),
      e('🚇', 'metro subway'),
      e('🚊', 'tram'),
      e('🚉', 'station'),
      e('✈️', 'airplane flight'),
      e('🛫', 'airplane departure'),
      e('🛬', 'airplane arrival'),
      e('🛩️', 'small airplane'),
      e('💺', 'seat'),
      e('🛰️', 'satellite'),
      e('🚀', 'rocket launch'),
      e('🛸', 'flying saucer ufo'),
      e('🚁', 'helicopter'),
      e('🛶', 'canoe kayak'),
      e('⛵', 'sailboat'),
      e('🚤', 'speedboat'),
      e('🛥️', 'motor boat'),
      e('🛳️', 'passenger ship'),
      e('⛴️', 'ferry'),
      e('🚢', 'ship'),
      e('⚓', 'anchor'),
      e('⛽', 'fuel pump gas'),
      e('🚧', 'construction barrier'),
      e('🚦', 'vertical traffic light'),
      e('🚥', 'horizontal traffic light'),
      e('🗺️', 'world map'),
      e('🗿', 'moai statue'),
      e('🗽', 'statue of liberty'),
      e('🗼', 'tokyo tower'),
      e('🏰', 'castle european'),
      e('🏯', 'castle japanese'),
      e('🏟️', 'stadium'),
      e('🎡', 'ferris wheel'),
      e('🎢', 'roller coaster'),
      e('🎠', 'carousel horse'),
      e('⛲', 'fountain'),
      e('⛱️', 'beach umbrella'),
      e('🏖️', 'beach'),
      e('🏝️', 'desert island'),
      e('🏜️', 'desert'),
      e('🌋', 'volcano'),
      e('⛰️', 'mountain'),
      e('🏔️', 'snow capped mountain'),
      e('🗻', 'mount fuji'),
      e('🏕️', 'camping'),
      e('⛺', 'tent'),
      e('🏠', 'house'),
      e('🏡', 'house with garden'),
      e('🏘️', 'houses'),
      e('🏚️', 'derelict house'),
      e('🏗️', 'construction'),
      e('🏭', 'factory'),
      e('🏢', 'office building'),
      e('🏬', 'department store'),
      e('🏣', 'japanese post office'),
      e('🏤', 'post office'),
      e('🏥', 'hospital'),
      e('🏦', 'bank'),
      e('🏨', 'hotel'),
      e('🏪', 'convenience store'),
      e('🏫', 'school'),
      e('🏩', 'love hotel'),
      e('💒', 'wedding chapel'),
      e('🏛️', 'classical building museum'),
      e('⛪', 'church'),
      e('🕌', 'mosque'),
      e('🕍', 'synagogue'),
      e('🛕', 'hindu temple'),
      e('🕋', 'kaaba'),
      e('⛩️', 'shinto shrine'),
      e('🌁', 'foggy'),
      e('🌃', 'night with stars'),
      e('🏙️', 'cityscape'),
      e('🌄', 'sunrise over mountains'),
      e('🌅', 'sunrise'),
      e('🌆', 'cityscape dusk'),
      e('🌇', 'sunset'),
      e('🌉', 'bridge night'),
      e('♨️', 'hot springs'),
      e('🎑', 'moon viewing ceremony'),
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    labelKey: 'objects',
    icon: '💡',
    emojis: [
      e('⌚', 'watch time'),
      e('📱', 'mobile phone'),
      e('📲', 'mobile phone arrow'),
      e('💻', 'laptop computer'),
      e('⌨️', 'keyboard'),
      e('🖥️', 'desktop computer'),
      e('🖨️', 'printer'),
      e('🖱️', 'computer mouse'),
      e('🖲️', 'trackball'),
      e('🕹️', 'joystick'),
      e('🗜️', 'clamp'),
      e('💽', 'minidisc'),
      e('💾', 'floppy disk save'),
      e('💿', 'cd disc'),
      e('📀', 'dvd'),
      e('📼', 'videocassette'),
      e('📷', 'camera'),
      e('📸', 'camera flash'),
      e('📹', 'video camera'),
      e('🎥', 'movie camera'),
      e('📽️', 'film projector'),
      e('🎞️', 'film frames'),
      e('📞', 'telephone receiver'),
      e('☎️', 'telephone'),
      e('📟', 'pager'),
      e('📠', 'fax'),
      e('📺', 'television tv'),
      e('📻', 'radio'),
      e('🎙️', 'studio microphone'),
      e('🎚️', 'level slider'),
      e('🎛️', 'control knobs'),
      e('🧭', 'compass'),
      e('⏱️', 'stopwatch'),
      e('⏲️', 'timer clock'),
      e('⏰', 'alarm clock'),
      e('🕰️', 'mantelpiece clock'),
      e('⌛', 'hourglass'),
      e('⏳', 'hourglass flowing'),
      e('📡', 'satellite antenna'),
      e('🔋', 'battery'),
      e('🔌', 'electric plug'),
      e('💡', 'light bulb idea'),
      e('🔦', 'flashlight torch'),
      e('🕯️', 'candle'),
      e('🪔', 'diya lamp'),
      e('🧯', 'fire extinguisher'),
      e('🛢️', 'oil drum'),
      e('💸', 'money with wings'),
      e('💵', 'dollar banknote'),
      e('💴', 'yen banknote'),
      e('💶', 'euro banknote'),
      e('💷', 'pound banknote'),
      e('🪙', 'coin'),
      e('💰', 'money bag'),
      e('💳', 'credit card'),
      e('💎', 'gem stone'),
      e('⚖️', 'balance scale'),
      e('🪜', 'ladder'),
      e('🧰', 'toolbox'),
      e('🪛', 'screwdriver'),
      e('🔧', 'wrench'),
      e('🔨', 'hammer'),
      e('⚒️', 'hammer and pick'),
      e('🛠️', 'hammer and wrench tools'),
      e('⛏️', 'pick'),
      e('🪚', 'carpentry saw'),
      e('🔩', 'nut and bolt'),
      e('⚙️', 'gear settings'),
      e('🪤', 'mouse trap'),
      e('🧱', 'brick'),
      e('⛓️', 'chains'),
      e('🧲', 'magnet'),
      e('🔫', 'water pistol'),
      e('💣', 'bomb'),
      e('🧨', 'firecracker'),
      e('🪓', 'axe'),
      e('🔪', 'kitchen knife'),
      e('🗡️', 'dagger'),
      e('⚔️', 'crossed swords'),
      e('🛡️', 'shield'),
      e('🚬', 'cigarette'),
      e('⚰️', 'coffin'),
      e('🪦', 'headstone'),
      e('⚱️', 'funeral urn'),
      e('🏺', 'amphora'),
      e('🔮', 'crystal ball'),
      e('📿', 'prayer beads'),
      e('🧿', 'nazar amulet'),
      e('💈', 'barber pole'),
      e('⚗️', 'alembic'),
      e('🔭', 'telescope'),
      e('🔬', 'microscope'),
      e('🕳️', 'hole'),
      e('🩹', 'adhesive bandage'),
      e('🩺', 'stethoscope'),
      e('💊', 'pill medicine'),
      e('💉', 'syringe'),
      e('🩸', 'drop of blood'),
      e('🧬', 'dna'),
      e('🦠', 'microbe germ virus'),
      e('🧫', 'petri dish'),
      e('🧪', 'test tube'),
      e('🌡️', 'thermometer'),
      e('🧹', 'broom'),
      e('🧺', 'basket'),
      e('🧻', 'roll of paper toilet'),
      e('🚽', 'toilet'),
      e('🚰', 'potable water'),
      e('🚿', 'shower'),
      e('🛁', 'bathtub'),
      e('🛀', 'person bath'),
      e('🧼', 'soap'),
      e('🪥', 'toothbrush'),
      e('🪒', 'razor'),
      e('🧽', 'sponge'),
      e('🪣', 'bucket'),
      e('🧴', 'lotion bottle'),
      e('🛎️', 'bellhop bell'),
      e('🔑', 'key'),
      e('🗝️', 'old key'),
      e('🚪', 'door'),
      e('🪑', 'chair'),
      e('🛋️', 'couch and lamp'),
      e('🛏️', 'bed'),
      e('🛌', 'sleeping bed'),
      e('🧸', 'teddy bear toy'),
      e('🖼️', 'framed picture'),
      e('🪞', 'mirror'),
      e('🪟', 'window'),
      e('🛍️', 'shopping bags'),
      e('🛒', 'shopping cart'),
      e('🎁', 'wrapped gift present'),
      e('🎈', 'balloon'),
      e('🎏', 'carp streamer'),
      e('🎀', 'ribbon'),
      e('🎊', 'confetti ball'),
      e('🎉', 'party popper celebration'),
      e('🎎', 'japanese dolls'),
      e('🏮', 'red paper lantern'),
      e('🎐', 'wind chime'),
      e('🧧', 'red envelope'),
      e('✉️', 'envelope email'),
      e('📩', 'envelope with arrow'),
      e('📨', 'incoming envelope'),
      e('📧', 'e-mail'),
      e('💌', 'love letter'),
      e('📥', 'inbox tray'),
      e('📤', 'outbox tray'),
      e('📦', 'package box'),
      e('🏷️', 'label tag'),
      e('🪧', 'placard sign'),
      e('📪', 'closed mailbox'),
      e('📫', 'closed mailbox with flag'),
      e('📬', 'open mailbox'),
      e('📭', 'open mailbox no mail'),
      e('📮', 'postbox'),
      e('📯', 'postal horn'),
      e('📜', 'scroll'),
      e('📃', 'page with curl'),
      e('📄', 'page facing up'),
      e('📑', 'bookmark tabs'),
      e('🧾', 'receipt'),
      e('📊', 'bar chart'),
      e('📈', 'chart increasing trending up'),
      e('📉', 'chart decreasing trending down'),
      e('🗒️', 'spiral notepad'),
      e('🗓️', 'spiral calendar'),
      e('📆', 'tear off calendar'),
      e('📅', 'calendar date'),
      e('🗑️', 'wastebasket trash'),
      e('📇', 'card index'),
      e('🗃️', 'card file box'),
      e('🗳️', 'ballot box'),
      e('🗄️', 'file cabinet'),
      e('📋', 'clipboard'),
      e('📁', 'file folder'),
      e('📂', 'open file folder'),
      e('🗂️', 'card index dividers'),
      e('🗞️', 'rolled up newspaper'),
      e('📰', 'newspaper'),
      e('📓', 'notebook journal'),
      e('📔', 'notebook with decorative cover'),
      e('📒', 'ledger'),
      e('📕', 'closed book red'),
      e('📗', 'green book'),
      e('📘', 'blue book'),
      e('📙', 'orange book'),
      e('📚', 'books'),
      e('📖', 'open book read'),
      e('🔖', 'bookmark'),
      e('🧷', 'safety pin'),
      e('🔗', 'link chain'),
      e('📎', 'paperclip'),
      e('🖇️', 'linked paperclips'),
      e('📐', 'triangular ruler'),
      e('📏', 'straight ruler'),
      e('🧮', 'abacus'),
      e('📌', 'pushpin'),
      e('📍', 'round pushpin location'),
      e('✂️', 'scissors'),
      e('🖊️', 'pen'),
      e('🖋️', 'fountain pen'),
      e('✒️', 'black nib'),
      e('🖌️', 'paintbrush'),
      e('🖍️', 'crayon'),
      e('📝', 'memo pencil note write'),
      e('✏️', 'pencil'),
      e('🔍', 'magnifying glass left search'),
      e('🔎', 'magnifying glass right'),
      e('🔏', 'locked with pen'),
      e('🔐', 'locked with key'),
      e('🔒', 'locked private'),
      e('🔓', 'unlocked'),
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    labelKey: 'symbols',
    icon: '❤️',
    emojis: [
      e('❤️', 'red heart love'),
      e('🧡', 'orange heart'),
      e('💛', 'yellow heart'),
      e('💚', 'green heart'),
      e('💙', 'blue heart'),
      e('💜', 'purple heart'),
      e('🖤', 'black heart'),
      e('🤍', 'white heart'),
      e('🤎', 'brown heart'),
      e('💔', 'broken heart'),
      e('❣️', 'heart exclamation'),
      e('💕', 'two hearts'),
      e('💞', 'revolving hearts'),
      e('💓', 'beating heart'),
      e('💗', 'growing heart'),
      e('💖', 'sparkling heart'),
      e('💘', 'heart arrow cupid'),
      e('💝', 'heart with ribbon gift'),
      e('💟', 'heart decoration'),
      e('☮️', 'peace'),
      e('✝️', 'latin cross'),
      e('☪️', 'star and crescent'),
      e('🕉️', 'om hindu'),
      e('☸️', 'wheel of dharma'),
      e('✡️', 'star of david'),
      e('🔯', 'six pointed star'),
      e('🕎', 'menorah'),
      e('☯️', 'yin yang'),
      e('☦️', 'orthodox cross'),
      e('🛐', 'place of worship'),
      e('⛎', 'ophiuchus'),
      e('♈', 'aries'),
      e('♉', 'taurus'),
      e('♊', 'gemini'),
      e('♋', 'cancer'),
      e('♌', 'leo'),
      e('♍', 'virgo'),
      e('♎', 'libra'),
      e('♏', 'scorpio'),
      e('♐', 'sagittarius'),
      e('♑', 'capricorn'),
      e('♒', 'aquarius'),
      e('♓', 'pisces'),
      e('🆔', 'id'),
      e('⚛️', 'atom science'),
      e('🉑', 'accept'),
      e('☢️', 'radioactive'),
      e('☣️', 'biohazard'),
      e('📴', 'mobile phone off'),
      e('📳', 'vibration mode'),
      e('🈶', 'not free of charge'),
      e('🈚', 'free of charge'),
      e('🈸', 'application'),
      e('🈺', 'open for business'),
      e('🈷️', 'monthly amount'),
      e('✴️', 'eight pointed star'),
      e('🆚', 'vs'),
      e('💮', 'white flower'),
      e('🉐', 'bargain'),
      e('㊙️', 'secret'),
      e('㊗️', 'congratulations'),
      e('🈴', 'passing grade'),
      e('🈵', 'no vacancy'),
      e('🈹', 'discount'),
      e('🈲', 'prohibited'),
      e('🅰️', 'a button blood'),
      e('🅱️', 'b button blood'),
      e('🆎', 'ab blood'),
      e('🆑', 'cl button'),
      e('🅾️', 'o button blood'),
      e('🆘', 'sos'),
      e('❌', 'cross mark x'),
      e('⭕', 'circle red'),
      e('🛑', 'stop sign'),
      e('⛔', 'no entry'),
      e('📛', 'name badge'),
      e('🚫', 'prohibited no'),
      e('💯', '100 perfect'),
      e('💢', 'anger'),
      e('♨️', 'hot springs'),
      e('🚷', 'no pedestrians'),
      e('🚯', 'no littering'),
      e('🚳', 'no bicycles'),
      e('🚱', 'non potable water'),
      e('🔞', 'no one under 18'),
      e('📵', 'no mobile phones'),
      e('🚭', 'no smoking'),
      e('❗', 'red exclamation'),
      e('❕', 'white exclamation'),
      e('❓', 'red question mark'),
      e('❔', 'white question mark'),
      e('‼️', 'double exclamation'),
      e('⁉️', 'exclamation question'),
      e('🔅', 'dim button low brightness'),
      e('🔆', 'bright button'),
      e('〽️', 'part alternation mark'),
      e('⚠️', 'warning'),
      e('🚸', 'children crossing'),
      e('🔱', 'trident'),
      e('⚜️', 'fleur de lis'),
      e('🔰', 'beginner'),
      e('♻️', 'recycle'),
      e('✅', 'check mark green'),
      e('🈯', 'reserved'),
      e('💹', 'chart increasing yen'),
      e('❇️', 'sparkle'),
      e('✳️', 'eight spoked asterisk'),
      e('❎', 'cross mark button'),
      e('🌐', 'globe meridians web'),
      e('💠', 'diamond with a dot'),
      e('Ⓜ️', 'circled m'),
      e('🌀', 'cyclone'),
      e('💤', 'zzz sleep'),
      e('🏧', 'atm sign'),
      e('🚾', 'wc water closet'),
      e('♿', 'wheelchair accessible'),
      e('🅿️', 'parking'),
      e('🈳', 'vacancy'),
      e('🈂️', 'service'),
      e('🛂', 'passport control'),
      e('🛃', 'customs'),
      e('🛄', 'baggage claim'),
      e('🛅', 'left luggage'),
      e('🚹', 'mens room'),
      e('🚺', 'womens room'),
      e('🚼', 'baby symbol'),
      e('🚻', 'restroom'),
      e('🚮', 'litter bin'),
      e('🎦', 'cinema'),
      e('📶', 'antenna bars signal'),
      e('🈁', 'here'),
      e('🔣', 'input symbols'),
      e('ℹ️', 'information'),
      e('🔤', 'input latin letters'),
      e('🔡', 'input lowercase'),
      e('🔠', 'input uppercase'),
      e('🆖', 'ng'),
      e('🆗', 'ok'),
      e('🆙', 'up'),
      e('🆒', 'cool'),
      e('🆕', 'new'),
      e('🆓', 'free'),
      e('0️⃣', 'zero'),
      e('1️⃣', 'one'),
      e('2️⃣', 'two'),
      e('3️⃣', 'three'),
      e('4️⃣', 'four'),
      e('5️⃣', 'five'),
      e('6️⃣', 'six'),
      e('7️⃣', 'seven'),
      e('8️⃣', 'eight'),
      e('9️⃣', 'nine'),
      e('🔟', 'ten'),
      e('🔢', 'input numbers'),
      e('#️⃣', 'hash'),
      e('*️⃣', 'asterisk'),
      e('⏏️', 'eject'),
      e('▶️', 'play'),
      e('⏸️', 'pause'),
      e('⏯️', 'play pause'),
      e('⏹️', 'stop'),
      e('⏺️', 'record'),
      e('⏭️', 'next track'),
      e('⏮️', 'previous track'),
      e('⏩', 'fast forward'),
      e('⏪', 'rewind'),
      e('⏫', 'fast up'),
      e('⏬', 'fast down'),
      e('◀️', 'reverse'),
      e('🔼', 'up button'),
      e('🔽', 'down button'),
      e('➡️', 'right arrow'),
      e('⬅️', 'left arrow'),
      e('⬆️', 'up arrow'),
      e('⬇️', 'down arrow'),
      e('↗️', 'up-right arrow'),
      e('↘️', 'down-right arrow'),
      e('↙️', 'down-left arrow'),
      e('↖️', 'up-left arrow'),
      e('↕️', 'up-down arrow'),
      e('↔️', 'left-right arrow'),
      e('↪️', 'right curve arrow'),
      e('↩️', 'left curve arrow'),
      e('⤴️', 'right arrow curving up'),
      e('⤵️', 'right arrow curving down'),
      e('🔀', 'shuffle'),
      e('🔁', 'repeat'),
      e('🔂', 'repeat one'),
      e('🔄', 'counterclockwise arrows'),
      e('🔃', 'clockwise vertical arrows'),
      e('🎵', 'musical note'),
      e('🎶', 'musical notes'),
      e('➕', 'plus'),
      e('➖', 'minus'),
      e('➗', 'divide'),
      e('✖️', 'multiply'),
      e('♾️', 'infinity'),
      e('💲', 'heavy dollar'),
      e('💱', 'currency exchange'),
      e('™️', 'trademark'),
      e('©️', 'copyright'),
      e('®️', 'registered'),
      e('〰️', 'wavy dash'),
      e('➰', 'curly loop'),
      e('➿', 'double curly loop'),
      e('🔚', 'end arrow'),
      e('🔙', 'back arrow'),
      e('🔛', 'on arrow'),
      e('🔝', 'top arrow'),
      e('🔜', 'soon arrow'),
      e('✔️', 'check mark'),
      e('☑️', 'check box with check'),
      e('🔘', 'radio button'),
      e('🔴', 'red circle'),
      e('🟠', 'orange circle'),
      e('🟡', 'yellow circle'),
      e('🟢', 'green circle'),
      e('🔵', 'blue circle'),
      e('🟣', 'purple circle'),
      e('⚫', 'black circle'),
      e('⚪', 'white circle'),
      e('🟤', 'brown circle'),
      e('🔺', 'red triangle up'),
      e('🔻', 'red triangle down'),
      e('🔸', 'small orange diamond'),
      e('🔹', 'small blue diamond'),
      e('🔶', 'large orange diamond'),
      e('🔷', 'large blue diamond'),
      e('🔳', 'white square button'),
      e('🔲', 'black square button'),
      e('▪️', 'black small square'),
      e('▫️', 'white small square'),
      e('◾', 'black medium-small square'),
      e('◽', 'white medium-small square'),
      e('◼️', 'black medium square'),
      e('◻️', 'white medium square'),
      e('🟥', 'red square'),
      e('🟧', 'orange square'),
      e('🟨', 'yellow square'),
      e('🟩', 'green square'),
      e('🟦', 'blue square'),
      e('🟪', 'purple square'),
      e('⬛', 'black large square'),
      e('⬜', 'white large square'),
      e('🟫', 'brown square'),
      e('🔈', 'speaker low volume'),
      e('🔇', 'muted speaker'),
      e('🔉', 'speaker medium volume'),
      e('🔊', 'speaker high volume'),
      e('🔔', 'bell'),
      e('🔕', 'bell with slash'),
      e('📣', 'megaphone'),
      e('📢', 'loudspeaker'),
      e('👁️‍🗨️', 'eye in speech bubble'),
      e('💬', 'speech balloon'),
      e('💭', 'thought balloon'),
      e('🗯️', 'right anger bubble'),
      e('♠️', 'spade suit'),
      e('♣️', 'club suit'),
      e('♥️', 'heart suit'),
      e('♦️', 'diamond suit'),
      e('🃏', 'joker card'),
      e('🎴', 'flower card'),
      e('🀄', 'mahjong red dragon'),
      e('🕐', '1 oclock'),
      e('🕑', '2 oclock'),
      e('🕒', '3 oclock'),
      e('🕓', '4 oclock'),
      e('🕔', '5 oclock'),
      e('🕕', '6 oclock'),
      e('🕖', '7 oclock'),
      e('🕗', '8 oclock'),
      e('🕘', '9 oclock'),
      e('🕙', '10 oclock'),
      e('🕚', '11 oclock'),
      e('🕛', '12 oclock'),
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    labelKey: 'flags',
    icon: '🚩',
    emojis: [
      e('🏁', 'chequered flag'),
      e('🚩', 'triangular flag'),
      e('🎌', 'crossed flags'),
      e('🏴', 'black flag'),
      e('🏳️', 'white flag'),
      e('🏳️‍🌈', 'rainbow flag pride lgbt'),
      e('🏳️‍⚧️', 'transgender flag'),
      e('🏴‍☠️', 'pirate flag'),
    ],
  },
]

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)
