//! Synthetic media bytes for demo seed (WAV, text, minimal JPEG) + Picsum fetch.

use std::f64::consts::PI;
use std::time::Duration;

/// Valid RIFF/WAVE PCM mono 16-bit little-endian sine tone (440 Hz).
pub fn synth_wav_tone(duration_ms: u32, sample_rate: u32) -> Vec<u8> {
    let sample_rate = sample_rate.max(1);
    let num_samples = ((sample_rate as u64).saturating_mul(duration_ms as u64) / 1000) as usize;
    let data_size = (num_samples * 2) as u32; // 16-bit mono
                                              // RIFF chunk size = "WAVE" + fmt(8+16) + data(8+data_size) = 36 + data_size
    let riff_size = 36u32.saturating_add(data_size);

    let mut out = Vec::with_capacity(44 + num_samples * 2);

    // RIFF header
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&riff_size.to_le_bytes());
    out.extend_from_slice(b"WAVE");

    // fmt chunk (PCM mono 16-bit)
    out.extend_from_slice(b"fmt ");
    out.extend_from_slice(&16u32.to_le_bytes()); // chunk size
    out.extend_from_slice(&1u16.to_le_bytes()); // audio format = PCM
    out.extend_from_slice(&1u16.to_le_bytes()); // channels = mono
    out.extend_from_slice(&sample_rate.to_le_bytes());
    let byte_rate = sample_rate.saturating_mul(2); // sample_rate * channels * bits/8
    out.extend_from_slice(&byte_rate.to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes()); // block align
    out.extend_from_slice(&16u16.to_le_bytes()); // bits per sample

    // data chunk
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_size.to_le_bytes());

    const FREQ_HZ: f64 = 440.0;
    const AMPLITUDE: f64 = 0.3;
    let sr = sample_rate as f64;
    for i in 0..num_samples {
        let t = i as f64 / sr;
        let sample = (AMPLITUDE * (2.0 * PI * FREQ_HZ * t).sin() * i16::MAX as f64) as i16;
        out.extend_from_slice(&sample.to_le_bytes());
    }

    out
}

/// Small UTF-8 demo note; returns `(bytes, extension without dot)` e.g. `"txt"`.
pub fn synth_text_file(name_hint: &str) -> (Vec<u8>, String) {
    let body = format!(
        "Memlore demo attachment\n\
         name: {name_hint}\n\
         This is a synthetic text file generated by the demo seed.\n"
    );
    (body.into_bytes(), "txt".to_string())
}

/// Download JPEG from Lorem Picsum. Follows redirects.
///
/// URL: `https://picsum.photos/seed/{seed}/{w}/{h}`
pub fn fetch_picsum_jpeg(seed: u32, w: u32, h: u32) -> Result<Vec<u8>, String> {
    let url = format!("https://picsum.photos/seed/{seed}/{w}/{h}");
    let client = reqwest::blocking::Client::builder()
        .redirect(reqwest::redirect::Policy::limited(10))
        .timeout(Duration::from_secs(30))
        .build()
        .map_err(|e| format!("picsum client: {e}"))?;

    let resp = client
        .get(&url)
        .send()
        .map_err(|e| format!("picsum request: {e}"))?;

    if !resp.status().is_success() {
        return Err(format!("picsum HTTP {}", resp.status()));
    }

    let bytes = resp.bytes().map_err(|e| format!("picsum body: {e}"))?;
    Ok(bytes.to_vec())
}

/// Tiny valid JPEG for tests (no network). 1×1 pixel, SOI…EOI.
pub fn minimal_jpeg_bytes() -> Vec<u8> {
    // Minimal JFIF 1×1 grey JPEG (known-good static fixture).
    vec![
        0xFF, 0xD8, // SOI
        0xFF, 0xE0, 0x00, 0x10, // APP0
        0x4A, 0x46, 0x49, 0x46, 0x00, // "JFIF\0"
        0x01, 0x01, // version 1.1
        0x00, // density units
        0x00, 0x01, 0x00, 0x01, // X/Y density
        0x00, 0x00, // thumbnail
        0xFF, 0xDB, 0x00, 0x43, 0x00, // DQT, length 67, table 0
        0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07, 0x07, 0x07, 0x09, 0x09, 0x08, 0x0A, 0x0C,
        0x14, 0x0D, 0x0C, 0x0B, 0x0B, 0x0C, 0x19, 0x12, 0x13, 0x0F, 0x14, 0x1D, 0x1A, 0x1F, 0x1E,
        0x1D, 0x1A, 0x1C, 0x1C, 0x20, 0x24, 0x2E, 0x27, 0x20, 0x22, 0x2C, 0x23, 0x1C, 0x1C, 0x28,
        0x37, 0x29, 0x2C, 0x30, 0x31, 0x34, 0x34, 0x34, 0x1F, 0x27, 0x39, 0x3D, 0x38, 0x32, 0x3C,
        0x2E, 0x33, 0x34, 0x32, // 64 quant values
        0xFF, 0xC0, 0x00, 0x0B, // SOF0, length 11
        0x08, // 8-bit
        0x00, 0x01, 0x00, 0x01, // 1×1
        0x01, // 1 component
        0x01, 0x11, 0x00, // id, sampling, quant table
        0xFF, 0xC4, 0x00, 0x1F, 0x00, // DHT DC table 0
        0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0xFF, 0xC4,
        0x00, 0xB5, 0x10, // DHT AC table 0
        0x00, 0x02, 0x01, 0x03, 0x03, 0x02, 0x04, 0x03, 0x05, 0x05, 0x04, 0x04, 0x00, 0x00, 0x01,
        0x7D, 0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21, 0x31, 0x41, 0x06, 0x13, 0x51,
        0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xA1, 0x08, 0x23, 0x42, 0xB1, 0xC1, 0x15,
        0x52, 0xD1, 0xF0, 0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0A, 0x16, 0x17, 0x18, 0x19, 0x1A,
        0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x43, 0x44,
        0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x63,
        0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A,
        0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98,
        0x99, 0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5,
        0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2,
        0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7,
        0xE8, 0xE9, 0xEA, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFF, 0xDA,
        0x00, 0x08, // SOS
        0x01, 0x01, 0x00, 0x00, 0x3F, 0x00, // scan header
        0x7F, // minimal entropy data
        0xFF, 0xD9, // EOI
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn synth_wav_is_riff_wave_with_payload() {
        let wav = synth_wav_tone(100, 8_000);
        assert!(
            wav.len() > 44,
            "expected non-trivial length for 100ms, got {}",
            wav.len()
        );
        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(&wav[8..12], b"WAVE");
        // PCM data: 8000 * 0.1 * 2 bytes = 1600, plus 44 header ≈ 1644
        assert!(
            wav.len() >= 44 + 1600,
            "expected at least header+PCM for 100ms@8kHz, got {}",
            wav.len()
        );
    }

    #[test]
    fn synth_text_file_is_utf8_txt() {
        let (bytes, ext) = synth_text_file("meeting-notes");
        assert_eq!(ext, "txt");
        assert!(!bytes.is_empty());
        let s = std::str::from_utf8(&bytes).expect("utf-8");
        assert!(s.contains("meeting-notes"));
    }

    #[test]
    fn minimal_jpeg_has_soi_eoi() {
        let jpeg = minimal_jpeg_bytes();
        assert!(jpeg.len() >= 4);
        assert_eq!(&jpeg[0..2], &[0xFF, 0xD8], "SOI");
        assert_eq!(&jpeg[jpeg.len() - 2..], &[0xFF, 0xD9], "EOI");
    }

    /// Network test — run with `cargo test media_synth -- --ignored`.
    #[test]
    #[ignore]
    fn fetch_picsum_jpeg_downloads_jpeg() {
        let bytes = fetch_picsum_jpeg(42, 64, 64).expect("picsum download");
        assert!(bytes.len() > 100, "expected real image bytes");
        assert_eq!(&bytes[0..2], &[0xFF, 0xD8], "JPEG SOI");
    }
}
